# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount
include: ['_pages/about.md']

# configuration required for some pages

domain: leok.me
title: leonardok
author: Leonardo
email: leokorndorfer@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-27240426-1


github:
  username: leonardok

# disqus:
#   id: disqusid
